apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlmodel-deployment
  labels:
    app: mlmodel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlmodel-deployment
  template:
    metadata:
      labels:
        app: mlmodel-deployment
    spec:
      containers:
        - name: mlmodel-deployment
          image: devesh77388/mlmodel-flask:21
          ports:
            - containerPort: 5000
