apiVersion: v1
kind: Service
metadata:
  name: mlmodel-deployment-service
spec:
  type: LoadBalancer
  selector:
    app: mlmodel-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
